version: '3.5'

services:
  db:
    container_name: pg_db_profileservice
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: profileService
    ports:
      - "5432:5442"
  pgadmin:
    container_name: pgadmin_profileservice
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hdnhdxv@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  ClientProfileService-app:
    build: ./
    container_name: 'java-app-ClientProfileService'
    image: client_profile_service-app
    ports:
      - "52561:52561"
    environment:
      SERVER_PORT: 52561
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db_profileservice:5432/profileService