server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: booking-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5437/booking

management:
  endpoints:
    web:
      exposure:
        include: "*"

  jpa:
    hibernate:
      ddl-auto: update
