version: '3'

services:
  db:
    container_name: pg_db_notificationService
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notificationService
    ports:
      - "5444:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOO_MY_ID: 1
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    ports:
      - "9092:9092"
      - "9093:9093"


  NotificationService-app:
    build: ./
    container_name: 'java-app-NotificationService'
    image: notification_service-app
    ports:
      - "52560:52560"
    environment:
      SERVER_PORT: 52560
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db_notificationService:5432/notificationService