#Eureka properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: DeliveryService

#General application status (End point)
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0

#Spring Cloud properties
spring:
  application:
    name: eclient_DeliveryService
  cloud:
    config:
      enabled: false
  #Database properties
  datasource:
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5436/blocked
    username: postgres
  #Hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
