#Eureka properties
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    appname: order-service
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

#Logger properties
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc: trace

server:
  port: 0

spring:
  application:
    name: OrderService
  #Database properties
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5445/order_database
    username: postgres
  #Hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
