version: '3.5'

services:
  db:
    container_name: pg_db_AuthenticationService
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authenticationService
    ports:
      - "5432:5433"
  pgadmin:
    container_name: pgadmin_root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hdnhdxv@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  AuthenticationService-app:
    build: ./
    container_name: 'java-app-AuthenticationService'
    image: authentication_service-app
    ports:
      - "52569:52569"
    environment:
      SERVER_PORT: 52569
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db_AuthenticationService:5432/authenticationService