#Eureka properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 0
spring:
  application:
    name: eclient_userInfoService
  #Database properties
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5447}/userInfo
    username: root
  #Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #Liquibase properties
  liquibase:
    change-log: classpath:db.changelog-master.yaml
    contexts: dev
    enabled: true

  #spring cloud
  cloud:
    stream:
      bindings:
        birthdayOutput:
          destination: email/birthday
          contentType: application/json
        sendBirthdayMessage-out-0:
          destination: birthdayGreetings
      kafka:
        binder:
          brokers: localhost:9092