version: '3.5'

services:
  db:
    image: postgres:16
    container_name: db_orderservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_database
    ports:
      - "5433:5445"

  OrderService-app:
    build: ./
    container_name: 'java-app-OrderService'
    image: order_service-app
    ports:
      - "52559:52559"
    environment:
      SERVER_PORT: 52559
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_orderservice:5432/order_database