version: '3.5'

services:
  EmailService-app:
    build: ./
    container_name: 'java-app-EmailService'
    image: email_service-app
    ports:
      - "52561:52561"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - eurekaserver_default

networks:
  eurekaserver_default:
    driver: bridge
    external: true
