#General application status (End point)
management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 0

#FreeMarker settings
spring:
  freemarker:
    check-template-location: false

  #Kafka properties
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: emailGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

cloud:
  stream:
    bindings:
      processBirthdayInfo-in-0:
        destination: birthdayGreetings
        group: emailGroup

  function:
    definition: processBirthdayInfo


  #Email configuration settings
  mail:
    host: smtp.mail.ru
    password: cMTiA1ZbZxz62jLeyFGq
    port: 587
    username: foma.kinyaev@internet.ru

