spring:
  profiles:
    active: git
  application:
    name: config-server
server:
  port: 8888
---
spring:
  profiles:
    active: git
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://gitpacket.kata.academy/scm/bus/ms-config-properties.git
          search-paths: "/{application}/{profile}"
          default-label: master
          username: anatoly_zakharov
          password: NjAxODM5NDQxOTY3OiaoekP7r42CdypCElrwhLFBFWM6

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, env, beans