#Eureka properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: ticketing-service
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 0
spring:
  application:
    name: TicketingService
  #Database properties
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5446}/ticketingService
    username: root
  #Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #Liquibase properties
  liquibase:
    change-log: classpath:db.changelog-master.yaml
    contexts: dev
    enabled: true