server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cancellation_service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5438/cancellationService
  jpa:
    hibernate:
      ddl-auto: update